language: ruby
cache: bundler
sudo: false

rvm:
- 2.0.0
- 2.1
- 2.2

branches:
  only:
    - master

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "sLJ7nThlmE2+xbLTS9+pUwU0eFWFI7ItwdKvFERId+nvxhI9MYdTlrQ5jlu+r11WfPsRer89bicRZrP19eWHJUMt5odObJ1xWY2VqSsEaU/f4J0/CTXHED8hIh87qj3naGqNFdAnquZ9MU9V5b7B3MZlnjQl/cShm8dGih3+oCVrvR8OQEH8PYMK/yL31v8S5VabMBq4row7NvvFTur6/9amHwKNQeQl5ZDEz8HnqQeNQLTQrTywwqpRw0X73u8TGm1AVZV5mEaB73O+6HUSofHIILoij41TfA+nYyLe/2w9iIbNl29y3nmw2GxU0cfj0Ku+Ijul6PyBidWpBn1DnJKx2S/ninRAXSHdrmm9ybCgmxSd8pHWM8YQTe/vLdx2jRwcujiTnaBAwYiDMIeidqusm2xcGfEfhOJRo5+NkaurfTJUWN6VOwVBZc7bYC6LfUdrZoqQGTPddXm2nFIblVwDx+fahyguxwO/9mpI6+uNWXyNQsE/I5+teWpAsiO6NVfKnyrCH/2ydZyoSv3qIpO42GncNkK/dQACRypkn4x+VfB/3Vvj4d+Ok0tk7n+MTU7u1BI2siOBHfw/CHOff8FmB8513Yb4p/+UHE75GNV+6ITDv7Y2J+3RssYQ1wHOODaOgthlUxM3B2MWBgb03iWX8TYyeDUttwGbRFmAkVk="
